name: JavaScript Unit, Integration, and Regression Tests

on:
  push:
    branches:
      - main
      - final
  pull_request:
    branches:
      - main
      - final

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: final

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Navigate to project directory
      run: cd path/to/your/project

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test
      env:
        TEST_PATTERN: 'advanced.test.js'

    - name: Run integration tests
      run: npm test
      env:
        TEST_PATTERN: 'basic.test.js'
